# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.23.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.23.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/amirmohammad/CLionProjects/DS-011-306-Programs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/amirmohammad/CLionProjects/DS-011-306-Programs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.23.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.23.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/amirmohammad/CLionProjects/DS-011-306-Programs/CMakeFiles /Users/amirmohammad/CLionProjects/DS-011-306-Programs//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/amirmohammad/CLionProjects/DS-011-306-Programs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named C1Q1

# Build rule for target.
C1Q1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 C1Q1
.PHONY : C1Q1

# fast build rule for target.
C1Q1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q1.dir/build.make CMakeFiles/C1Q1.dir/build
.PHONY : C1Q1/fast

#=============================================================================
# Target rules for targets named C1Q2

# Build rule for target.
C1Q2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 C1Q2
.PHONY : C1Q2

# fast build rule for target.
C1Q2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q2.dir/build.make CMakeFiles/C1Q2.dir/build
.PHONY : C1Q2/fast

#=============================================================================
# Target rules for targets named C1Q3

# Build rule for target.
C1Q3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 C1Q3
.PHONY : C1Q3

# fast build rule for target.
C1Q3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q3.dir/build.make CMakeFiles/C1Q3.dir/build
.PHONY : C1Q3/fast

#=============================================================================
# Target rules for targets named C1Q6

# Build rule for target.
C1Q6: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 C1Q6
.PHONY : C1Q6

# fast build rule for target.
C1Q6/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q6.dir/build.make CMakeFiles/C1Q6.dir/build
.PHONY : C1Q6/fast

#=============================================================================
# Target rules for targets named C1Q7

# Build rule for target.
C1Q7: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 C1Q7
.PHONY : C1Q7

# fast build rule for target.
C1Q7/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q7.dir/build.make CMakeFiles/C1Q7.dir/build
.PHONY : C1Q7/fast

#=============================================================================
# Target rules for targets named C1Q8

# Build rule for target.
C1Q8: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 C1Q8
.PHONY : C1Q8

# fast build rule for target.
C1Q8/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q8.dir/build.make CMakeFiles/C1Q8.dir/build
.PHONY : C1Q8/fast

#=============================================================================
# Target rules for targets named C1Q9

# Build rule for target.
C1Q9: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 C1Q9
.PHONY : C1Q9

# fast build rule for target.
C1Q9/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q9.dir/build.make CMakeFiles/C1Q9.dir/build
.PHONY : C1Q9/fast

#=============================================================================
# Target rules for targets named C1Q10

# Build rule for target.
C1Q10: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 C1Q10
.PHONY : C1Q10

# fast build rule for target.
C1Q10/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q10.dir/build.make CMakeFiles/C1Q10.dir/build
.PHONY : C1Q10/fast

#=============================================================================
# Target rules for targets named C1Q11

# Build rule for target.
C1Q11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 C1Q11
.PHONY : C1Q11

# fast build rule for target.
C1Q11/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q11.dir/build.make CMakeFiles/C1Q11.dir/build
.PHONY : C1Q11/fast

#=============================================================================
# Target rules for targets named C1Q14

# Build rule for target.
C1Q14: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 C1Q14
.PHONY : C1Q14

# fast build rule for target.
C1Q14/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q14.dir/build.make CMakeFiles/C1Q14.dir/build
.PHONY : C1Q14/fast

#=============================================================================
# Target rules for targets named C1Q15

# Build rule for target.
C1Q15: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 C1Q15
.PHONY : C1Q15

# fast build rule for target.
C1Q15/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q15.dir/build.make CMakeFiles/C1Q15.dir/build
.PHONY : C1Q15/fast

#=============================================================================
# Target rules for targets named C1Q16

# Build rule for target.
C1Q16: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 C1Q16
.PHONY : C1Q16

# fast build rule for target.
C1Q16/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q16.dir/build.make CMakeFiles/C1Q16.dir/build
.PHONY : C1Q16/fast

Chapter1/Q1.o: Chapter1/Q1.cpp.o
.PHONY : Chapter1/Q1.o

# target to build an object file
Chapter1/Q1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q1.dir/build.make CMakeFiles/C1Q1.dir/Chapter1/Q1.cpp.o
.PHONY : Chapter1/Q1.cpp.o

Chapter1/Q1.i: Chapter1/Q1.cpp.i
.PHONY : Chapter1/Q1.i

# target to preprocess a source file
Chapter1/Q1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q1.dir/build.make CMakeFiles/C1Q1.dir/Chapter1/Q1.cpp.i
.PHONY : Chapter1/Q1.cpp.i

Chapter1/Q1.s: Chapter1/Q1.cpp.s
.PHONY : Chapter1/Q1.s

# target to generate assembly for a file
Chapter1/Q1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q1.dir/build.make CMakeFiles/C1Q1.dir/Chapter1/Q1.cpp.s
.PHONY : Chapter1/Q1.cpp.s

Chapter1/Q10.o: Chapter1/Q10.cpp.o
.PHONY : Chapter1/Q10.o

# target to build an object file
Chapter1/Q10.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q10.dir/build.make CMakeFiles/C1Q10.dir/Chapter1/Q10.cpp.o
.PHONY : Chapter1/Q10.cpp.o

Chapter1/Q10.i: Chapter1/Q10.cpp.i
.PHONY : Chapter1/Q10.i

# target to preprocess a source file
Chapter1/Q10.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q10.dir/build.make CMakeFiles/C1Q10.dir/Chapter1/Q10.cpp.i
.PHONY : Chapter1/Q10.cpp.i

Chapter1/Q10.s: Chapter1/Q10.cpp.s
.PHONY : Chapter1/Q10.s

# target to generate assembly for a file
Chapter1/Q10.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q10.dir/build.make CMakeFiles/C1Q10.dir/Chapter1/Q10.cpp.s
.PHONY : Chapter1/Q10.cpp.s

Chapter1/Q11.o: Chapter1/Q11.cpp.o
.PHONY : Chapter1/Q11.o

# target to build an object file
Chapter1/Q11.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q11.dir/build.make CMakeFiles/C1Q11.dir/Chapter1/Q11.cpp.o
.PHONY : Chapter1/Q11.cpp.o

Chapter1/Q11.i: Chapter1/Q11.cpp.i
.PHONY : Chapter1/Q11.i

# target to preprocess a source file
Chapter1/Q11.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q11.dir/build.make CMakeFiles/C1Q11.dir/Chapter1/Q11.cpp.i
.PHONY : Chapter1/Q11.cpp.i

Chapter1/Q11.s: Chapter1/Q11.cpp.s
.PHONY : Chapter1/Q11.s

# target to generate assembly for a file
Chapter1/Q11.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q11.dir/build.make CMakeFiles/C1Q11.dir/Chapter1/Q11.cpp.s
.PHONY : Chapter1/Q11.cpp.s

Chapter1/Q14.o: Chapter1/Q14.cpp.o
.PHONY : Chapter1/Q14.o

# target to build an object file
Chapter1/Q14.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q14.dir/build.make CMakeFiles/C1Q14.dir/Chapter1/Q14.cpp.o
.PHONY : Chapter1/Q14.cpp.o

Chapter1/Q14.i: Chapter1/Q14.cpp.i
.PHONY : Chapter1/Q14.i

# target to preprocess a source file
Chapter1/Q14.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q14.dir/build.make CMakeFiles/C1Q14.dir/Chapter1/Q14.cpp.i
.PHONY : Chapter1/Q14.cpp.i

Chapter1/Q14.s: Chapter1/Q14.cpp.s
.PHONY : Chapter1/Q14.s

# target to generate assembly for a file
Chapter1/Q14.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q14.dir/build.make CMakeFiles/C1Q14.dir/Chapter1/Q14.cpp.s
.PHONY : Chapter1/Q14.cpp.s

Chapter1/Q15.o: Chapter1/Q15.cpp.o
.PHONY : Chapter1/Q15.o

# target to build an object file
Chapter1/Q15.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q15.dir/build.make CMakeFiles/C1Q15.dir/Chapter1/Q15.cpp.o
.PHONY : Chapter1/Q15.cpp.o

Chapter1/Q15.i: Chapter1/Q15.cpp.i
.PHONY : Chapter1/Q15.i

# target to preprocess a source file
Chapter1/Q15.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q15.dir/build.make CMakeFiles/C1Q15.dir/Chapter1/Q15.cpp.i
.PHONY : Chapter1/Q15.cpp.i

Chapter1/Q15.s: Chapter1/Q15.cpp.s
.PHONY : Chapter1/Q15.s

# target to generate assembly for a file
Chapter1/Q15.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q15.dir/build.make CMakeFiles/C1Q15.dir/Chapter1/Q15.cpp.s
.PHONY : Chapter1/Q15.cpp.s

Chapter1/Q16.o: Chapter1/Q16.cpp.o
.PHONY : Chapter1/Q16.o

# target to build an object file
Chapter1/Q16.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q16.dir/build.make CMakeFiles/C1Q16.dir/Chapter1/Q16.cpp.o
.PHONY : Chapter1/Q16.cpp.o

Chapter1/Q16.i: Chapter1/Q16.cpp.i
.PHONY : Chapter1/Q16.i

# target to preprocess a source file
Chapter1/Q16.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q16.dir/build.make CMakeFiles/C1Q16.dir/Chapter1/Q16.cpp.i
.PHONY : Chapter1/Q16.cpp.i

Chapter1/Q16.s: Chapter1/Q16.cpp.s
.PHONY : Chapter1/Q16.s

# target to generate assembly for a file
Chapter1/Q16.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q16.dir/build.make CMakeFiles/C1Q16.dir/Chapter1/Q16.cpp.s
.PHONY : Chapter1/Q16.cpp.s

Chapter1/Q2.o: Chapter1/Q2.cpp.o
.PHONY : Chapter1/Q2.o

# target to build an object file
Chapter1/Q2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q2.dir/build.make CMakeFiles/C1Q2.dir/Chapter1/Q2.cpp.o
.PHONY : Chapter1/Q2.cpp.o

Chapter1/Q2.i: Chapter1/Q2.cpp.i
.PHONY : Chapter1/Q2.i

# target to preprocess a source file
Chapter1/Q2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q2.dir/build.make CMakeFiles/C1Q2.dir/Chapter1/Q2.cpp.i
.PHONY : Chapter1/Q2.cpp.i

Chapter1/Q2.s: Chapter1/Q2.cpp.s
.PHONY : Chapter1/Q2.s

# target to generate assembly for a file
Chapter1/Q2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q2.dir/build.make CMakeFiles/C1Q2.dir/Chapter1/Q2.cpp.s
.PHONY : Chapter1/Q2.cpp.s

Chapter1/Q3.o: Chapter1/Q3.cpp.o
.PHONY : Chapter1/Q3.o

# target to build an object file
Chapter1/Q3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q3.dir/build.make CMakeFiles/C1Q3.dir/Chapter1/Q3.cpp.o
.PHONY : Chapter1/Q3.cpp.o

Chapter1/Q3.i: Chapter1/Q3.cpp.i
.PHONY : Chapter1/Q3.i

# target to preprocess a source file
Chapter1/Q3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q3.dir/build.make CMakeFiles/C1Q3.dir/Chapter1/Q3.cpp.i
.PHONY : Chapter1/Q3.cpp.i

Chapter1/Q3.s: Chapter1/Q3.cpp.s
.PHONY : Chapter1/Q3.s

# target to generate assembly for a file
Chapter1/Q3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q3.dir/build.make CMakeFiles/C1Q3.dir/Chapter1/Q3.cpp.s
.PHONY : Chapter1/Q3.cpp.s

Chapter1/Q6.o: Chapter1/Q6.cpp.o
.PHONY : Chapter1/Q6.o

# target to build an object file
Chapter1/Q6.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q6.dir/build.make CMakeFiles/C1Q6.dir/Chapter1/Q6.cpp.o
.PHONY : Chapter1/Q6.cpp.o

Chapter1/Q6.i: Chapter1/Q6.cpp.i
.PHONY : Chapter1/Q6.i

# target to preprocess a source file
Chapter1/Q6.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q6.dir/build.make CMakeFiles/C1Q6.dir/Chapter1/Q6.cpp.i
.PHONY : Chapter1/Q6.cpp.i

Chapter1/Q6.s: Chapter1/Q6.cpp.s
.PHONY : Chapter1/Q6.s

# target to generate assembly for a file
Chapter1/Q6.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q6.dir/build.make CMakeFiles/C1Q6.dir/Chapter1/Q6.cpp.s
.PHONY : Chapter1/Q6.cpp.s

Chapter1/Q7.o: Chapter1/Q7.cpp.o
.PHONY : Chapter1/Q7.o

# target to build an object file
Chapter1/Q7.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q7.dir/build.make CMakeFiles/C1Q7.dir/Chapter1/Q7.cpp.o
.PHONY : Chapter1/Q7.cpp.o

Chapter1/Q7.i: Chapter1/Q7.cpp.i
.PHONY : Chapter1/Q7.i

# target to preprocess a source file
Chapter1/Q7.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q7.dir/build.make CMakeFiles/C1Q7.dir/Chapter1/Q7.cpp.i
.PHONY : Chapter1/Q7.cpp.i

Chapter1/Q7.s: Chapter1/Q7.cpp.s
.PHONY : Chapter1/Q7.s

# target to generate assembly for a file
Chapter1/Q7.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q7.dir/build.make CMakeFiles/C1Q7.dir/Chapter1/Q7.cpp.s
.PHONY : Chapter1/Q7.cpp.s

Chapter1/Q8.o: Chapter1/Q8.cpp.o
.PHONY : Chapter1/Q8.o

# target to build an object file
Chapter1/Q8.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q8.dir/build.make CMakeFiles/C1Q8.dir/Chapter1/Q8.cpp.o
.PHONY : Chapter1/Q8.cpp.o

Chapter1/Q8.i: Chapter1/Q8.cpp.i
.PHONY : Chapter1/Q8.i

# target to preprocess a source file
Chapter1/Q8.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q8.dir/build.make CMakeFiles/C1Q8.dir/Chapter1/Q8.cpp.i
.PHONY : Chapter1/Q8.cpp.i

Chapter1/Q8.s: Chapter1/Q8.cpp.s
.PHONY : Chapter1/Q8.s

# target to generate assembly for a file
Chapter1/Q8.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q8.dir/build.make CMakeFiles/C1Q8.dir/Chapter1/Q8.cpp.s
.PHONY : Chapter1/Q8.cpp.s

Chapter1/Q9.o: Chapter1/Q9.cpp.o
.PHONY : Chapter1/Q9.o

# target to build an object file
Chapter1/Q9.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q9.dir/build.make CMakeFiles/C1Q9.dir/Chapter1/Q9.cpp.o
.PHONY : Chapter1/Q9.cpp.o

Chapter1/Q9.i: Chapter1/Q9.cpp.i
.PHONY : Chapter1/Q9.i

# target to preprocess a source file
Chapter1/Q9.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q9.dir/build.make CMakeFiles/C1Q9.dir/Chapter1/Q9.cpp.i
.PHONY : Chapter1/Q9.cpp.i

Chapter1/Q9.s: Chapter1/Q9.cpp.s
.PHONY : Chapter1/Q9.s

# target to generate assembly for a file
Chapter1/Q9.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/C1Q9.dir/build.make CMakeFiles/C1Q9.dir/Chapter1/Q9.cpp.s
.PHONY : Chapter1/Q9.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... C1Q1"
	@echo "... C1Q10"
	@echo "... C1Q11"
	@echo "... C1Q14"
	@echo "... C1Q15"
	@echo "... C1Q16"
	@echo "... C1Q2"
	@echo "... C1Q3"
	@echo "... C1Q6"
	@echo "... C1Q7"
	@echo "... C1Q8"
	@echo "... C1Q9"
	@echo "... Chapter1/Q1.o"
	@echo "... Chapter1/Q1.i"
	@echo "... Chapter1/Q1.s"
	@echo "... Chapter1/Q10.o"
	@echo "... Chapter1/Q10.i"
	@echo "... Chapter1/Q10.s"
	@echo "... Chapter1/Q11.o"
	@echo "... Chapter1/Q11.i"
	@echo "... Chapter1/Q11.s"
	@echo "... Chapter1/Q14.o"
	@echo "... Chapter1/Q14.i"
	@echo "... Chapter1/Q14.s"
	@echo "... Chapter1/Q15.o"
	@echo "... Chapter1/Q15.i"
	@echo "... Chapter1/Q15.s"
	@echo "... Chapter1/Q16.o"
	@echo "... Chapter1/Q16.i"
	@echo "... Chapter1/Q16.s"
	@echo "... Chapter1/Q2.o"
	@echo "... Chapter1/Q2.i"
	@echo "... Chapter1/Q2.s"
	@echo "... Chapter1/Q3.o"
	@echo "... Chapter1/Q3.i"
	@echo "... Chapter1/Q3.s"
	@echo "... Chapter1/Q6.o"
	@echo "... Chapter1/Q6.i"
	@echo "... Chapter1/Q6.s"
	@echo "... Chapter1/Q7.o"
	@echo "... Chapter1/Q7.i"
	@echo "... Chapter1/Q7.s"
	@echo "... Chapter1/Q8.o"
	@echo "... Chapter1/Q8.i"
	@echo "... Chapter1/Q8.s"
	@echo "... Chapter1/Q9.o"
	@echo "... Chapter1/Q9.i"
	@echo "... Chapter1/Q9.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

